import Head from "next/head";
import Image from "next/image";

import Hero from "../components/Hero";
import About from "../components/About";
import Testimonails from "../components/Testimonials";
import CallToAction from "../components/CallToAction";

export default function Home() {
  return (
    <div>
      <Head>
        <title>ECJJA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <main>
        <About />
        <CallToAction />
        <Testimonails />
      </main>
    </div>
  );
}
